# Generated by Django 6.1.1 on 2026-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learners', to='core.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_to_teach',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.skill'),
        ),
    ]
